### ISSUE TITLE
android.app.Application cannot be cast to 

### ISSUE THREAD

**Issue by yairvillarp** [mocaplatform/moca-phonegap-sdk#13]
Hi, im building an app with ionic and moca and i got this error:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ionicframework.nbapp945542/com.ionicframework.nbapp945542.MainActivity}: java.lang.ClassCastException: android.app.Application cannot be cast to com.innoquant.moca.phonegap.MOCApp`

it seems that i just got the issue that you people say about the manifest change.

**Comment by tomacco** [comment]
Yair, the description of this error and its solution are posted here:

http://developer.mocaplatform.com/docs/common-issues-troubleshooting#application-crashes-at-startup
